# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /evernet-eg

# Title of the Site
title: Evernet eG
# Description of the Site
description: Breitbandversorgung - ländlicher Raum
# URL of Image of the Site
#site-image: /WhatATheme/assets/images/meta.jpg
site-image: /assets/images/meta.jpg
# Logo URL for Navi
site-logo: /assets/images/logo.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /assets/images/background-splash.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info@evernet-eg.de
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
#github_username:  thedevslot
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: /assets/images/logo_sqr.png
# 60 Words About the Author
author-about: Wir bieten die Möglichkeit einer Breitbandversorgung in ländlichen Gebieten, die keinen oder nur eingeschränkten Internetzugang haben. Dazu verwenden wir eine auf Funk basierende Kommunikationsstruktur.<br/><br/>Derzeit haben wir - neben Sundhausen - drei weitere Gemeinden mit unserer Funktechnik vernetzt. Hier können wir Bandbreiten von bis zu 48 MBit zur Verfügung stellen.<br/><br/>Auf Wunsch sind auch Punkt-zu-Punkt-Verbindungen mit höheren Bandbreiten möglich.<br/><br/>Auch wenn Sie sich nicht in unserem unmittelbaren Einzugsgebiet befinden, stehen wir Ihnen gern mit unserem Know-How zur Verfügung.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
